# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Install deps
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - public
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - store_artifacts:
          path: stats.html
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy JS
          command: aws s3 sync public/js s3://richardnias.com/js --region eu-west-2 --cache-control "max-age=2628000, immutable" --content-encoding "gzip"
      - run:
          name: Deploy HTML
          command: aws s3 sync public s3://richardnias.com --region eu-west-2 --exclude "js" --cache-control "max-age=3600" --content-encoding "gzip"
      - run:
          name: Deploy robots.txt
          command: aws s3 sync src s3://richardnias.com --region eu-west-2 --include "robots.txt" --cache-control "max-age=3600"
  lighthouse:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install lighthouse
      - run: npm run lighthouse
      - store_artifacts:
          path: lighthouse.html
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  weekly:
    triggers:
      - schedule:
          cron: "0 12 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - lighthouse
